AllCops:
  Include:
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'
    - 'config/initializers/generators.rb'
    - 'config/unicorn.rb'

# Allow dots at the end of lines when chaining methods
# that span multiple lines
DotPosition:
  Enabled: false

LineLength:
  Enabled: false

Documentation:
  Enabled: false

MethodLength:
  CountComments: false
  Max: 15

Metrics/ClassLength:
  CountComments: false
  Max: 100

Style/GuardClause:
  MinBodyLength: 3

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/ScopeArgs:
  Enabled: false

Style/AndOr:
  # Whether `and` and `or` are banned only in conditionals (conditionals)
  # or completely (always).
  EnforcedStyle: conditionals
