HOST: http://ohanapi.herokuapp.com

--- Ohana REST API v1 ---
---
REST API for San Mateo County human services, parks, farmers' markets, and other community-based agencies.
---

--
List of fields

`accessibility_options`: Array
`agency`: String
`ask_for`: Array
`city`: String
`coordinates`: Array
`descriptions`: String
`eligibility_requirements`: String
`emails`: Array
`faxes`: Array
`fees`: String
`funding_sources`: Array
`how_to_apply`: String
`keywords`: Array 
`languages_spoken`: Array
`latitude`: Float
`leaders`: Array
`longitude`: Float
`market_match`: Boolean
`name`: String
`payments_accepted`: Array
`phones`: Array
`products_sold`: Array
`service_areas`: Array
`service_hours`: String
`service_wait`: String
`services_provided`: String
`state`: String
`street_address`: String
`target_group`: String
`transportation_availability`: String
`ttys`: Array 
`urls`: Array
`zipcode`: String
--

-- Organizations Resources --
Returns a paginated list of all organizations (30 per page) sorted alphabetically in ascending order.
Pagination information is included at the bottom of the response. You can specify further pages with the `?page` parameter. For example, to view the second page: `api/organizations?page=2`
This request is cached for 5 minutes.

GET api/organizations
> Accept: application/vnd.ohanapi+json; version=1
< 200
< Content-Type: application/json; charset=utf-8
< Cache-Control: max-age=300, public
{
response: [
{
_id: "51a9fd0328217f89770001b2",
accessibility_options: [
"Varies according to location"
],
agency: "San Mateo County Parks Department.",
ask_for: "Park Ranger",
business_hours: null,
city: "Woodside",
coordinates: [
-122.291251,
37.432594
],
description: "A hillside area of redwood forest with picnic sites, 26 miles of hiking and horse trails, playground, archery range and shelter buildings. Docents conduct nature walks by appointment. (call 650-591-1085.) Pets are not allowed in the park. The Chickadee Nature Trail and the Werder picnic and play area are accessible to those with disabilities. Sequoia Day Camp, built for summertime use by the Girl Scouts, is available for families and groups by reservation if not in use by Girl Scouts Day Camps. It offers 30 camp areas, an amphitheater, lawns and a restroom. It can accommodate approximately 200 people and is totally accessible to disabled persons. Group camping in three areas holding up to 50 people per area is available by reservation only. No family camping.",
eligibility_requirements: "None",
emails: null,
faxes: [
"650 851-9558"
],
fees: "$5 per car. Open group areas rent for a minimum of $225-$300 (varies by site), buildings for $300 a day. $150 per night for group camping. Cash accepted",
funding_sources: null,
how_to_apply: "Phone 650-363-4021 for group permits or go on-line at www.eparks.net",
keywords: [
"RECREATION/LEISURE SERVICES",
"Camping",
"Parks/Playground",
"City/County Parks"
],
languages_spoken: null,
latitude: null,
leaders: null,
longitude: null,
market_match: null,
name: "Huddart Park.",
payments_accepted: null,
phones: [
[
{
number: "650 851-1210",
department: "Information",
phone_hours: "(Monday-Friday, 9-12, 1-5)"
}
],
[
{
number: "650 851-0326",
department: "Huddart Park",
phone_hours: "(Saturday, Sunday)"
}
],
[
{
number: "650 363-4021",
department: "Reservations"
}
]
],
products_sold: null,
service_areas: ["San Mateo County"],
service_hours: "Opens at 8 am; closing times posted and vary by season",
service_wait: "Varies according to season",
services_provided: "Picnic sites, hiking and horse trails, playground, archery range.",
state: "CA",
street_address: "1100 Kings Mountain Road",
target_group: "Families, corporations, hikers, equestrians, joggers, nature lovers",
transportation_availability: "No public transportation",
ttys: [
"650 325-6973"
],
urls: [
"http://www.eparks.net"
],
zipcode: "94062"
}
],
count: 30,
pagination: {
previous: null,
next: 2,
current: 1,
per_page: 30,
count: 1734,
pages: 58
}
}

Retrieve an organization's information. This request is cached for 5 minutes.
GET api/organizations/{id}
> Accept: application/vnd.ohanapi+json; version=1
< 200
< Content-Type: application/json; charset=utf-8
< Cache-Control: max-age=300, public
{
response: {
_id: "51a9fd0828217f89770005e3",
accessibility_options: [
"Restroom",
"Special parking",
"Wheelchair accessible"
],
agency: "San Mateo County Health System. Behavioral Health and Recovery Services.",
ask_for: null,
city: "Belmont",
coordinates: null,
description: "Administers and monitors programs to prevent and treat alcohol and substance abuse in San Mateo County.",
eligibility_requirements: "None",
emails: null,
faxes: [
"650 802-6440"
],
fees: "None",
funding_sources: ["County"],
how_to_apply: "Call for information",
keywords: [
"ADMINISTRATION AND PLANNING SERVICES",
"Administration and Planning",
"Substance Abuse Education/Prevention",
"Administrative Entities"
],
languages_spoken: [
"Filipino (Tagalog)",
"Hindi",
"Panjabi",
"Spanish",
"Urdu"
],
latitude: null,
leaders: ["Christine O'Kelly (Supervisor)", "Isabelle M. Valderrama (Administrative Secretary)"]
longitude: null,
market_match: null,
name: "Administration., Alcohol and Other Drug Services.",
payments_accepted: null,
phones: [
[
{
number: "650 802-6400",
phone_hours: "(Monday-Friday, 8-5)"
}
]
],
products_sold: null,
service_hours: "Monday-Friday, 8-5",
service_wait: "No wait",
services_provided: "Administers and monitors programs to prevent and treat alcohol and substance abuse in San Mateo County.",
state: "CA",
street_address: "400 Harbor Blvd., Building C",
target_group: null,
transportation_availability: "CALTRAIN and SAMTRANS stop within 4 blocks",
ttys: null,
urls: [
"http://www.sanmateo.networkofcare.org"
],
zipcode: "94002-4047"
}
}

-- 
Search 

Returns a paginated list of search results (30 per page). Pagination information is included at the bottom of the response. You can specify further pages with the `?page` parameter. For example, to view the second page: `api/search?keyword=parks&page=2`.

All search results are cached for 5 minutes.

**Accepted parameters and values:**

`keyword`: Any search term

`location`: A valid full address (street address, city, state), or `city, state`, or 5-digit ZIP code

`radius`: A number between 0.1 and 10 (miles)

`sort` (*Optional*): `name`

`order` (*Optional*): one of `asc` or `desc`

If a search query contains neither `keyword` nor `location`, it will return an error.

Searches that include the `location` parameter will be sorted by distance by default. To sort them by name, add `&sort=name` to the query. When the `order` parameter is not present, the sort will be in ascending order by default. For descending order, add `&order=desc` to the query. 

Searches that don't include the `location` parameter will be sorted alphabetically in ascending order. For descending order, add `&order=desc` to the query.
--

GET api/search{?keyword,location,radius,sort,order}
> Accept: application/vnd.ohanapi+json; version=1
< 200
< Content-Type: application/json; charset=utf-8
< Cache-Control: max-age=300, public
{
response: [
{
_id: "51a9fd0728217f897700047e",
accessibility_options: [
"Wheelchair accessible"
],
agency: "YMCA of Silicon Valley.",
ask_for: ["Whoever answers the phone"],
city: "San Jose",
coordinates: null,
description: "Provides activities for children, teens, adults, seniors and families such as sports, child care, teen leadership, health enhancement, swim lessons, resident camp and day camping. Also provides tutoring services, computer training and CPR/first aid classes.",
eligibility_requirements: "None",
emails: null,
faxes: null,
fees: "Vary according to income and program activities. Financial assistance available. Cash, checks and credit cards accepted",
funding_sources: ["County"],
how_to_apply: "Walk in, apply by phone or mail",
keywords: [
"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES",
"Parent Groups",
"RECREATION/LEISURE SERVICES",
"Camping",
"Parks/Playground",
"Special Events/Entertainment",
"Sports/Games/Exercise",
"Y Facilities"
],
languages_spoken: null,
latitude: null,
leaders: null,
longitude: null,
market_match: null,
name: "Administration.",
payments_accepted: null,
phones: [
[
{
number: "408 351-6400",
phone_hours: "(Monday-Friday, 8-5)"
}
]
],
products_sold: null,
service_hours: "Vary according to location and program",
service_wait: "No wait",
services_provided: "Provides activities for adults, youth and families including sports, childcare, youth leadership, health enhancement and camping.",
state: "CA",
street_address: "1922 The Alameda, 3rd Floor",
target_group: null,
transportation_availability: "Varies according to program site",
ttys: null,
urls: [
"http://www.ymcasv.org"
],
zipcode: "95126"
},
{
_id: "51a9fd0428217f89770002bd",
accessibility_options: [
"Wheelchair accessible"
],
agency: "YMCA of San Francisco.",
ask_for: ["Whoever answers the phone"],
business_hours: null,
city: "San Francisco",
coordinates: null,
description: "Administers all the programs and services of the 15 YMCA branch sites. The YMCA provides a variety of services to improve existing problems in the community. These include health, exercise and fitness, recreation, guidance and counseling including mentoring, youth development, parent education, neighborhood and community development, day and resident camps, YMCA Camp Jones Gulch overnight camp in La Honda (described separately), swimming and aquatics, licensed child care and senior centers. See branch office descriptions for specific programs.",
eligibility_requirements: "None",
emails: [
"info@ymcasf.org"
],
faxes: [
"415 777-6915"
],
fees: "Vary according to service. Limited financial assistance available. Cash, checks and credit cards accepted",
funding_sources: ["County"],
how_to_apply: "Apply by phone or walk in at closest branch site (see phone book for locations)",
keywords: [
"ADMINISTRATION AND PLANNING SERVICES",
"Administration and Planning",
"RECREATION/LEISURE SERVICES",
"Camping",
"Parks/Playground",
"Y Facilities"
],
languages_spoken: null,
latitude: null,
leaders: null,
longitude: null,
market_match: null,
name: "Association Office.",
payments_accepted: null,
phones: [
[
{
number: "415 777-9622",
phone_hours: "(Monday-Friday, 8:30-5:30)"
}
]
],
products_sold: null,
service_hours: "Vary",
service_wait: "Varies",
services_provided: "Administers all the programs and services of the YMCA branch sites.",
state: "CA",
street_address: "631 Howard Street, Suite 500",
target_group: "Focus is on programs/services for youth and teens but the YMCA is open to all",
transportation_availability: "Varies according to location",
ttys: null,
urls: [
"http://www.ymcasf.org"
],
zipcode: "94105"
},
{
    more results
}
],
count: 30,
pagination: {
previous: null,
next: 2,
current: 1,
per_page: 30,
count: 57,
pages: 2
}
}