version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/ohana-api
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres@db"
      DOCKER_DB_HOST: 'db'
    depends_on:
      - db
