version: '2'
services:
  web:
    build: .
    volumes:
      - .:/ohana-api
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres@db"
    depends_on:
      - db
  db:
    image: postgres
