# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause this
# file to always be loaded, without a need to explicitly require it in any files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, make a
# separate helper file that requires this one and then use it only in the specs
# that actually need it.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  config.after(:suite) do
    if File.exist?("#{Rails.root}/tmp/archive.zip")
      File.delete("#{Rails.root}/tmp/archive.zip")
    end
  end

  # allows you to run only the failures from the previous run:
  # rspec --only-failures
  config.example_status_persistence_file_path = './tmp/rspec-examples.txt'

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  # config.profile_examples = 10

  # # rspec-expectations config goes here. You can use an alternate
  # # assertion/expectation library such as wrong or the stdlib/minitest
  # # assertions if you prefer.
  # config.expect_with :rspec do |expectations|
  #   # Enable only the newer, non-monkey-patching expect syntax.
  #   # For more details, see:
  #   #   - http://myronmars.to/n/dev-blog/2012/06/rspecs-new-expectation-syntax
  #   expectations.syntax = :expect
  # end

  # # rspec-mocks config goes here. You can use an alternate test double
  # # library (such as bogus or mocha) by changing the `mock_with` option here.
  # config.mock_with :rspec do |mocks|
  #   # Enable only the newer, non-monkey-patching expect syntax.
  #   # For more details, see:
  #   #   - http://teaisaweso.me/blog/2013/05/27/rspecs-new-message-expectation-syntax/
  #   mocks.syntax = :expect

  #   # Prevents you from mocking or stubbing a method that does not exist on
  #   # a real object. This is generally recommended.
  #   mocks.verify_partial_doubles = true
  # end
end
