#!/bin/sh

set -e

echo "===> Bundling..."
bundle install

if [ ! -f config/application.yml ]; then
  echo 'Setting default environment variables...'
  cp config/application.example.yml config/application.yml
fi

script/setup_db
