#!/bin/sh

set -e

echo "===> Exporting the ohana_api_development DB into data/ohana_api_development.dump"
pg_dump -Fc --no-acl --no-owner -h localhost ohana_api_development > data/ohana_api_development.dump
echo "===> Done exporting the DB."