#!/bin/sh

set -e

echo "===> Resetting the database..."
bin/rake db:reset
echo "===> Done resetting the DB."

echo "===> Populating the DB from data/ohana_api_development.dump..."
pg_restore -c --no-owner -d ohana_api_development data/ohana_api_development.dump
echo "===> Done populating the DB."

echo "===> All done!"