#!/bin/sh

set -e

echo "===> Resetting the database..."
bin/rake db:reset
echo "===> Done resetting the DB."

echo "===> Populating the DB via dump file"
pg_restore -c --no-owner -d ohana_api_smc_development data/ohana_api_smc_test.dump
echo "===> Done populating the DB."

echo "===> All done!"
