#!/bin/sh

set -e

echo "===> Restoring the DB from data/ohana_api_development.dump..."
pg_restore -c --no-owner -d ohana_api_development data/ohana_api_development.dump
echo "===> Done restoring the DB."
