#!/bin/sh

set -e

echo "===> Creating ohana-api_production database..."
rake db:create:all
echo "===> Loading the DB schema..."
rake db:schema:load

echo "===> Populating up the DB..."
rake setup_db

script/tire