#!/bin/sh

set -e

if [ $1 ]
then
  herokuApp="$1"

  echo "Getting ready to set environment variables for $herokuApp"
  figaro heroku:set -e production

  echo "Setting MAILER_URL"
  heroku config:set MAILER_URL=$herokuApp.herokuapp.com --app $herokuApp

  echo "Setting DEVISE_SECRET_KEY"
  # generate a random string with 36 characters
  token1=$(python -c 'import uuid; print uuid.uuid4()')
  heroku config:set DEVISE_SECRET_KEY=$token1 --app $herokuApp

  echo "Setting SECRET_TOKEN"
  # generate a random string with 36 characters
  token2=$(python -c 'import uuid; print uuid.uuid4()')
  heroku config:set SECRET_TOKEN=$token2 --app $herokuApp

  echo "Getting ready to install add-ons for $herokuApp"

  echo "Installing Postgres"
  heroku addons:add heroku-postgresql --app $herokuApp

  echo "Installing Mandrill by MailChimp"
  heroku addons:add mandrill --app $herokuApp

  echo "Installing Memcachier"
  heroku addons:add memcachier --app $herokuApp

  echo "All done setting up env vars and add-ons."
  echo "Pushing code to Heroku now. This will take a few minutes..."
  git push heroku master

  heroku run script/setup_prod_db --app $herokuApp
else
  echo "Please add your Heroku app name to the end of the command."
  echo "Usage: setup_heroku your_app_name"
fi
